name: Export

on:
  push:

jobs:
  export-gltf:
    name: Export gltf
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install blender

    - name: Generate gltf
      run: scripts/export-all.py
